# .NET Desktop

# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'
  #name: OData
  #demands:
  #  - Agent.Name -equals ODataBuild26
  

variables:
#   solution: 'sln\OData.Net45.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'
  skipComponentGovernanceDetection: true

steps:

- script: |
   echo Write your commands here
   
   echo Hello world
   
   dotnet.exe --info
   

  displayName: 'Command Line Script'

- task: DotNetCoreCLI@2

  displayName: 'dotnet build'

  inputs:

    projects: '$(Build.SourcesDirectory)\src\Microsoft.Spatial\Microsoft.Spatial.csproj'

# - task: PowerShell@2
#   inputs:
#     filePath: 'build.ps1'
#     arguments: 'EnableSkipStrongName'
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#     projects: 'test\FunctionalTests\Microsoft.Spatial.Tests\Microsoft.Spatial.Tests.csproj'
#     arguments: '--collect "Code coverage"'


# #  - task: BatchScript@1
# #    displayName: 'Run script - EnableSkipStrongName'
# #    inputs:
#       filename: '$(Build.SourcesDirectory)\build.cmd'
#       arguments: EnableSkipStrongName
#       modifyEnvironment: false

