blank_issues_enabled: false
contact_links:
  - name: â“ General Questions & Support
    url: https://github.com/OData/odata.net/discussions
    about: "For general questions, please use GitHub Discussions instead of opening an issue."
